
CREATE TABLE CLIENTES
(
    ID_CLIENTE NUMBER NOT NULL,
    NOMBRE VARCHAR2(200),
    AP_PATERNO VARCHAR2(200),
    AP_MATERNO VARCHAR2(200),
    TELEFONO VARCHAR2(45),
    CONSTRAINT CLIENTE_PK PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE ESCUELAS
(
    ID_ESCUELA NUMBER NOT NULL,
    NOMBRE VARCHAR2(200),
    ESCUDO VARCHAR2(200),
    DIRECCION VARCHAR(200),
    CCT VARCHAR2(50),
    NIVEL VARCHAR2(200),
    CONSTRAINT ESCUELA_PK PRIMARY KEY(ID_ESCUELA)
);

CREATE TABLE UNIFORMES
(
    ID_UNIFORME NUMBER NOT NULL,
    ESCUELA_ID NUMBER NOT NULL,
    TIPO_UNIFORME VARCHAR2(200),
    DESCRIPCION VARCHAR2(200),
    TIPO_MATERIAL VARCHAR(200),
    COLOR VARCHAR2(200),
    PRECIO FLOAT,
    CONSTRAINT UNIFORME_PK PRIMARY KEY(ID_UNIFORME),
    CONSTRAINT ESCUELA_FK FOREIGN KEY(ESCUELA_ID)
    REFERENCES ESCUELAS(ID_ESCUELA)
);


CREATE TABLE PEDIDOS
(
    ID_PEDIDO NUMBER NOT NULL,
    UNIFORME_ID NUMBER NOT NULL,
    CLIENTE_ID NUMBER NOT NULL,
    CANTIDAD NUMBER,
    FECHA_SOLICITUD DATE,
    FECHA_ENTREGA DATE,
    ANTICIPO FLOAT,
    ESTATUS VARCHAR2(50),
    DESCRIPCION VARCHAR2(500),
    TALLA NUMBER,
    CONSTRAINT PEDIDOS_PK PRIMARY KEY(ID_PEDIDO),
    CONSTRAINT UNIFORME_FK FOREIGN KEY(UNIFORME_ID)
    REFERENCES UNIFORMES(ID_UNIFORME),
    CONSTRAINT CLIENTE_FK FOREIGN KEY(CLIENTE_ID)
    REFERENCES CLIENTES(ID_CLIENTE)
);


CREATE TABLE TALLERES
(
    ID_TALLER NUMBER NOT NULL,
    NUM_TALLER NUMBER,
    NOMBRE VARCHAR2(200),
    DIRECCION VARCHAR2(200),
    TELEFONO VARCHAR2(45),
    NUMERO_TRABAJADOR NUMBER,
    CONSTRAINT TALLERES_PK PRIMARY KEY(ID_TALLER)
);


CREATE TABLE CAPTURAS
(
    ID_CAPTURA NUMBER NOT NULL,
    TALLER_ID NUMBER NOT NULL,
    PEDIDO_ID NUMBER NOT NULL,
    FECHA_CAPTURA DATE,
    CONSTRAINT CAPTURAS_PK PRIMARY KEY(ID_CAPTURA),
    CONSTRAINT TALLER_FK FOREIGN KEY(TALLER_ID)
    REFERENCES TALLERES(ID_TALLER),
    CONSTRAINT PEDIDOS_FK FOREIGN KEY(PEDIDO_ID)
    REFERENCES PEDIDOS(ID_PEDIDO)
);

--DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE6"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;
 
 --DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE7"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;
 
 --DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE8"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;
 
 --DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE9"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;
 
 --DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE10"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;   
    
 --DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE11"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;   

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, AP_PATERNO, AP_MATERNO, TELEFONO)
VALUES
(SEQUENCE6.NEXTVAL, 'MARGARITA','MORALES','SEGUNDO','2225252525');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, AP_PATERNO, AP_MATERNO, TELEFONO)
VALUES
(SEQUENCE6.NEXTVAL, 'PEDRO','HERNANDEZ','HUGO','8758587657');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, AP_PATERNO, AP_MATERNO, TELEFONO)
VALUES
(SEQUENCE6.NEXTVAL, 'MARIA','TOMAS','MORALES','3526178238');

INSERT INTO ESCUELAS (ID_ESCUELA, NOMBRE, ESCUDO, DIRECCION, CCT, NIVEL) 
VALUES
(SEQUENCE7.NEXTVAL, 'MIGUEL HIDALGO', 'LOGO DE MIGUEL', 'JALPA DE LOS BANOS', 'PRIM-7635', 'PRIMARIA');

INSERT INTO ESCUELAS (ID_ESCUELA, NOMBRE, ESCUDO, DIRECCION, CCT, NIVEL) 
VALUES
(SEQUENCE7.NEXTVAL, 'JUANA DE ARCO', 'LOGO DE JUANA', 'ATLACOMULCO', 'JA-9879E32', 'PREPARATORIA');

INSERT INTO ESCUELAS (ID_ESCUELA, NOMBRE, ESCUDO, DIRECCION, CCT, NIVEL) 
VALUES
(SEQUENCE7.NEXTVAL, 'FRANCISCO VILLA', 'LOGO DE FRANCISCO', 'AZCAPOTZALCO', 'AZCP-354353', 'PRESCOLAR');

INSERT INTO UNIFORMES (ID_UNIFORME, ESCUELA_ID, TIPO_UNIFORME, DESCRIPCION, TIPO_MATERIAL, COLOR, PRECIO)
VALUES
(SEQUENCE8.NEXTVAL, 1, 'DEPORTIVO','MANGAS COLOR MARINO, CON FRANJAS BLANCAS','CEDA','ROJO',500.0);

INSERT INTO UNIFORMES (ID_UNIFORME, ESCUELA_ID, TIPO_UNIFORME, DESCRIPCION, TIPO_MATERIAL, COLOR, PRECIO)
VALUES
(SEQUENCE8.NEXTVAL, 1, 'DEPORTIVO','2 FRANJAS BLANCAS Y CON CIERRE EN LAS BOLSAS','SPUM','NEGRO',450.0);

INSERT INTO UNIFORMES (ID_UNIFORME, ESCUELA_ID, TIPO_UNIFORME, DESCRIPCION, TIPO_MATERIAL, COLOR, PRECIO)
VALUES
(SEQUENCE8.NEXTVAL, 1, 'GALA','SUETER CON DOS LINEAS BLANCAS','ESTAMBRE','MARINO',200.0);


INSERT INTO PEDIDOS(ID_PEDIDO, UNIFORME_ID, CLIENTE_ID, CANTIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, ANTICIPO, ESTATUS, DESCRIPCION, TALLA)
VALUES 
(SEQUENCE9.NEXTVAL, 2,1,2,TO_DATE('2023-10-11 13:00.00', 'YYYY-MM-DD HH24:mi:ss'),TO_DATE('2023-10-12 13:00.00', 'YYYY-MM-DD HH24:mi:ss'),200.0,'EN ESPERA','NINGUNA', 12);


INSERT INTO PEDIDOS(ID_PEDIDO, UNIFORME_ID, CLIENTE_ID, CANTIDAD, FECHA_SOLICITUD, FECHA_ENTREGA, ANTICIPO, ESTATUS, DESCRIPCION, TALLA)
VALUES 
(SEQUENCE9.NEXTVAL, 1,2,10,TO_DATE('2023-11-12 13:00.00', 'YYYY-MM-DD HH24:mi:ss'),TO_DATE('2023-12-20 13:00.00', 'YYYY-MM-DD HH24:mi:ss'),9000.0,'EN PRODUCCION','SOLICITA 1 MUESTRA', 20);

INSERT INTO TALLERES(ID_TALLER, NUM_TALLER, NOMBRE, DIRECCION, TELEFONO,NUMERO_TRABAJADOR)
VALUES
(SEQUENCE10.NEXTVAL, 1056,'TALLER 1','SAN AGUSTIN','7123458675',10);

INSERT INTO TALLERES(ID_TALLER, NUM_TALLER, NOMBRE, DIRECCION, TELEFONO,NUMERO_TRABAJADOR)
VALUES
(SEQUENCE10.NEXTVAL, 1446,'TALLER 2','SAN ANGEL','5523458675',5);


INSERT INTO CAPTURAS (ID_CAPTURA, TALLER_ID, PEDIDO_ID, FECHA_CAPTURA)
VALUES
(SEQUENCE11.NEXTVAL, 1, 1,TO_DATE('2023-02-23 13:00.00', 'YYYY-MM-DD HH24:mi:ss')); 

INSERT INTO CAPTURAS (ID_CAPTURA, TALLER_ID, PEDIDO_ID, FECHA_CAPTURA)
VALUES
(SEQUENCE11.NEXTVAL, 2, 2,TO_DATE('2023-03-12 13:00.00', 'YYYY-MM-DD HH24:mi:ss'));



SELECT * FROM UNIFORMES;
SELECT * FROM PEDIDOS;
SELECT * FROM CLIENTES;
SELECT * FROM ESCUELAS;
SELECT * FROM TALLERES;
SELECT * FROM CAPTURAS;

