
CREATE TABLE CLIENTES
(
    ID_CLIENTE NUMBER NOT NULL,
    NOMBRE VARCHAR2(200),
    AP_PATERNO VARCHAR2(200),
    AP_MATERNO VARCHAR2(200),
    TELEFONO VARCHAR2(45),
    CONSTRAINT CLIENTE_PK PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE ESCUELAS
(
    ID_ESCUELA NUMBER NOT NULL,
    NOMBRE VARCHAR2(200),
    ESCUDO VARCHAR2(200),
    DIRECCION VARCHAR(200),
    CCT VARCHAR2(50),
    NIVEL VARCHAR2(200),
    CONSTRAINT ESCUELA_PK PRIMARY KEY(ID_ESCUELA)
);

CREATE TABLE UNIFORMES
(
    ID_UNIFORME NUMBER NOT NULL,
    ESCUELA_ID NUMBER NOT NULL,
    TIPO_UNIFORME VARCHAR2(200),
    DESCRIPCION VARCHAR2(200),
    TIPO_MATERIAL VARCHAR(200),
    COLOR VARCHAR2(200),
    PRECIO FLOAT,
    CONSTRAINT UNIFORME_PK PRIMARY KEY(ID_UNIFORME),
    CONSTRAINT ESCUELA_FK FOREIGN KEY(ESCUELA_ID)
    REFERENCES ESCUELAS(ID_ESCUELA)
);

SELECT * FROM UNIFORMES;


CREATE TABLE PEDIDOS
(
    ID_PEDIDO NUMBER NOT NULL,
    UNIFORME_ID NUMBER NOT NULL,
    CLIENTE_ID NUMBER NOT NULL,
    CANTIDAD NUMBER,
    FECHA_SOLICITUD DATE,
    FECHA_ENTREGA DATE,
    ANTICIPO FLOAT,
    ESTATUS VARCHAR2(50),
    DESCRIPCION VARCHAR2(500),
    TALLA NUMBER,
    CONSTRAINT PEDIDOS_PK PRIMARY KEY(ID_PEDIDO),
    CONSTRAINT UNIFORME_FK FOREIGN KEY(UNIFORME_ID)
    REFERENCES UNIFORMES(ID_UNIFORME),
    CONSTRAINT CLIENTE_FK FOREIGN KEY(CLIENTE_ID)
    REFERENCES CLIENTES(ID_CLIENTE)
);


CREATE TABLE TALLERES
(
    ID_TALLER NUMBER NOT NULL,
    NUM_TALLER NUMBER,
    NOMBRE VARCHAR2(200),
    DIRECCION VARCHAR2(200),
    TELEFONO VARCHAR2(45),
    NUMERO_TRABAJADOR NUMBER,
    CONSTRAINT TALLERES_PK PRIMARY KEY(ID_TALLER)
);


CREATE TABLE CAPTURAS
(
    ID_CAPTURA NUMBER NOT NULL,
    TALLER_ID NUMBER NOT NULL,
    PEDIDO_ID NUMBER NOT NULL,
    FECHA_CAPTURA DATE,
    CONSTRAINT CAPTURAS_PK PRIMARY KEY(ID_CAPTURA),
    CONSTRAINT TALLER_FK FOREIGN KEY(TALLER_ID)
    REFERENCES TALLERES(ID_TALLER),
    CONSTRAINT PEDIDOS_FK FOREIGN KEY(PEDIDO_ID)
    REFERENCES PEDIDOS(ID_PEDIDO)
);




--DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE6"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;
 
 --DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE7"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;
 
    
INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, AP_PATERNO, AP_MATERNO, TELEFONO)
VALUES
(SEQUENCE6.NEXTVAL, 'MARGARITA','MORALES','SEGUNDO','2225252525');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, AP_PATERNO, AP_MATERNO, TELEFONO)
VALUES
(SEQUENCE6.NEXTVAL, 'PEDRO','HERNANDEZ','HUGO','8758587657');

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, AP_PATERNO, AP_MATERNO, TELEFONO)
VALUES
(SEQUENCE6.NEXTVAL, 'MARIA','TOMAS','MORALES','3526178238');

INSERT INTO 







