CREATE TABLE CHOFERES
(
    ID_CHOFER NUMBER NOT NULL,
    NOMBRE VARCHAR2(200),
    AP_PATERNO VARCHAR2(200),
    AP_MATERNO VARCHAR2(200),
    LICENCIA VARCHAR2(45),
    TELEFONO VARCHAR2(45),
    FECHA_NACIMIENTO DATE,
    DISPONIBILIDAD NUMBER,
    CONSTRAINT CHOFERES_PK PRIMARY KEY(ID_CHOFER) 
);

CREATE TABLE CAMIONES
(
    ID_CAMION NUMBER NOT NULL,
    MATRICULA VARCHAR2(45),
    TIPO_CAMION VARCHAR2(45),
    MODELO NUMBER,
    MARCA VARCHAR2(45),
    CAPACIDAD NUMBER,
    KILOMETRAJE FLOAT,
    DISPONIBILIDAD NUMBER,
    CONSTRAINT CAMIONES_PK PRIMARY KEY(ID_CAMION)
);



CREATE TABLE DIRECCIONES 
(
   ID_DIRECCION NUMBER NOT NULL,
   CALLE VARCHAR2(45),
   NUMERO VARCHAR2(45),
   COLONIA VARCHAR2(45),
   CIUDAD VARCHAR2(45),
   ESTADO VARCHAR2(45),
   CP VARCHAR2(45),
   CONSTRAINT DIRECCIONES_PK PRIMARY KEY(ID_DIRECCION)
);

--DDL PARA LA DEFINICION DE LA TABLA RUTAS

CREATE TABLE RUTAS
(
    ID_RUTA NUMBER NOT NULL,
    CAMION_ID NUMBER NOT NULL,
    CHOFER_ID NUMBER NOT NULL,
    DIRECCION_ORIGEN_ID NUMBER NOT NULL,
    DIRECCION_DESTINO_ID NUMBER NOT NULL,
    DISTANCIA FLOAT,
    FECHA_SALIDA DATE,
    FECHA_LLEGADA_ESTIMADA DATE,
    FECHA_LLEGADA_REAL DATE,
    A_TIEMPO NUMBER,
    CONSTRAINT RUTAS_PK PRIMARY KEY (ID_RUTA),
    --DEFINICION DE LAS LLAVES FORANEAS
    CONSTRAINT RUTAS_CHOFERES_FK FOREIGN KEY(CHOFER_ID)
        REFERENCES CHOFERES(ID_CHOFER),
    CONSTRAINT RUTAS_CAMIONES_FK FOREIGN KEY(CAMION_ID)
        REFERENCES CAMIONES(ID_CAMION),
    CONSTRAINT RUTAS_ORIGEN_FK FOREIGN KEY(DIRECCION_ORIGEN_ID)
        REFERENCES DIRECCIONES(ID_DIRECCION),
    CONSTRAINT RUTAS_DESTINO_FK FOREIGN KEY(DIRECCION_DESTINO_ID)
        REFERENCES DIRECCIONES(ID_DIRECCION)
);


--DDL PARA LA DEFINICION DE LA TABLA CARGAMENTOS
CREATE TABLE CARGAMENTOS
(
    ID_CARGAMENTO NUMBER NOT NULL,
    RUTA_ID NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(45),
    PESO FLOAT,
    ESTATUS NUMBER,
    CONSTRAINT CARGAMENTOS_PK PRIMARY KEY (ID_CARGAMENTO),
    CONSTRAINT CARGAMENTOS_RUTAS_FK FOREIGN KEY(RUTA_ID)
        REFERENCES RUTAS(ID_RUTA) 
);


--DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE1"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;
    
    --DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE2"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;
--DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE3"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;
    
--DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE4"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;
--DDL PARA LA DEFINICION DE UNA SECUENCIA
CREATE SEQUENCE "SEQUENCE5"
    MINVALUE 1
    MAXVALUE 9999999999999999999999999999
    INCREMENT BY 1
    START WITH 1;






--DML PARA LA INSERCION DE UN CHOFER

INSERT INTO CHOFERES (ID_CHOFER, NOMBRE, AP_PATERNO, AP_MATERNO, 
LICENCIA, TELEFONO, FECHA_NACIMIENTO, DISPONIBILIDAD)
VALUES
(SEQUENCE1.NEXTVAL, 'JAVIER','TORRES','TIMAL','FR-1212', '2225252525',
TO_DATE('2020-10-10 13:00.00', 'YYYY-MM-DD HH24:mi:ss'),1);


INSERT INTO CHOFERES (ID_CHOFER, NOMBRE, AP_PATERNO, AP_MATERNO, 
LICENCIA, TELEFONO, FECHA_NACIMIENTO, DISPONIBILIDAD)
VALUES
(SEQUENCE1.NEXTVAL, 'ERWIN','LOPEZ','JIMENEZ','EL-2024', '35346252525',
TO_DATE('2000-11-01 13:00.00', 'YYYY-MM-DD HH24:mi:ss'),1);

--ESCRIBIR EL DML PARA LA INSERCION DE 2 CAMIONES

INSERT INTO CAMIONES (ID_CAMION, MATRICULA, TIPO_CAMION, MODELO, MARCA, CAPACIDAD, KILOMETRAJE, DISPONIBILIDAD)
VALUES
(SEQUENCE2.NEXTVAL, 'TRUCK-1010','TRAILER',2020, 'INTERNATIONAL',10000, 50000.0,1);

INSERT INTO CAMIONES (ID_CAMION, MATRICULA, TIPO_CAMION, MODELO, MARCA, CAPACIDAD, KILOMETRAJE, DISPONIBILIDAD)
VALUES
(SEQUENCE2.NEXTVAL, 'TRUCK-2010','3 EJES',2015, 'VOLVO',8000, 45000.0,1);

--ESCRIBIR EL DML PARA LA INSERCION DE 2 DIRECCIONES

INSERT INTO DIRECCIONES(ID_DIRECCION, CALLE, NUMERO, COLONIA, CIUDAD, ESTADO, CP)
VALUES
(SEQUENCE3.NEXTVAL, 'Otumba', '54', 'Narvarte', 'Ciudad de Mexico', 'Ciudad de Mexico', '30987');

INSERT INTO DIRECCIONES(ID_DIRECCION, CALLE, NUMERO, COLONIA, CIUDAD, ESTADO, CP)
VALUES
(SEQUENCE3.NEXTVAL, 'Las primaveras', '21', 'Norte 45', 'Torreon', 'Coahuila', '10586');

--ESCRIBIR EL DML PARA LA INSERCION DE 2 RUTAS

INSERT INTO RUTAS (ID_RUTA, CAMION_ID, CHOFER_ID, DIRECCION_ORIGEN_ID, DIRECCION_DESTINO_ID, 
DISTANCIA, FECHA_SALIDA, FECHA_LLEGADA_ESTIMADA, FECHA_LLEGADA_REAL, A_TIEMPO)
VALUES
(SEQUENCE4.NEXTVAL, 1,2,1,2,45.8,
TO_DATE('2024-01-09 13:00.00', 'YYYY-MM-DD HH24:mi:ss'),
TO_DATE('2024-01-10 13:00.00', 'YYYY-MM-DD HH24:mi:ss'),
TO_DATE('2024-01-10 13:00.00', 'YYYY-MM-DD HH24:mi:ss'),1);


INSERT INTO RUTAS (ID_RUTA, CAMION_ID, CHOFER_ID, DIRECCION_ORIGEN_ID, DIRECCION_DESTINO_ID, 
DISTANCIA, FECHA_SALIDA, FECHA_LLEGADA_ESTIMADA, FECHA_LLEGADA_REAL, A_TIEMPO)
VALUES
(SEQUENCE4.NEXTVAL, 2,1,2,1,35.3,
TO_DATE('2024-01-10 13:00.00', 'YYYY-MM-DD HH24:mi:ss'),
TO_DATE('2024-01-10 13:00.00', 'YYYY-MM-DD HH24:mi:ss'),
TO_DATE('2024-01-11 13:00.00', 'YYYY-MM-DD HH24:mi:ss'),0);
--ESCRIBIR EL DML PARA LA INSERCION DE 2 CARGAMENTO

INSERT INTO CARGAMENTOS(ID_CARGAMENTO, RUTA_ID, DESCRIPCION, PESO, ESTATUS)
VALUES
(SEQUENCE5.NEXTVAL,1,'CARGA DE ROPA',200,1);

INSERT INTO CARGAMENTOS(ID_CARGAMENTO, RUTA_ID, DESCRIPCION, PESO, ESTATUS)
VALUES
(SEQUENCE5.NEXTVAL,1,'CARGA DE MAIZ',1000,0);


--CONSULTAS DE LISTADO DE CADA TABLA
SELECT * FROM CARGAMENTOS;
SELECT * FROM CHOFERES;
SELECT * FROM DIRECCIONES;
SELECT * FROM RUTAS;
SELECT * FROM CARGAMENTOS;



SELECT NOMBRE, LICENCIA FROM CHOFERES WHERE CHOFERES.NOMBRE = 'ERWIN'; 




CREATE OR REPLACE FUNCTION SUMA(X NUMBER, Y NUMBER)
	RETURN NUMBER
IS
	SUMA NUMBER;
BEGIN
	SUMA:= X + Y;
	RETURN X + Y;
END;


CREATE OR REPLACE FUNCTION CALCULARSUELDO(RUTAS_TERMINADAS NUMBER)
    RETURN NUMBER
IS
    SUELDO NUMBER;
BEGIN
    SUELDO:= RUTAS_TERMINADAS * 100;
    RETURN SUELDO;
END;


SELECT CALACULARSUELDO(3) FROM DUAL;


SELECT * FROM CAMIONES;


SELECT * FROM CAMIONES WHERE ID_CAMION = 1;

SELECT a.direccion_origen_id ,C.CALLE,C.ESTADO, A.DISTANCIA, B.MARCA, B.CAPACIDAD
FROM RUTAS A
JOIN CAMIONES B ON A.CAMION_ID = B.ID_CAMION
JOIN DIRECCIONES C ON a.direccion_origen_id = c.id_direccion WHERE a.direccion_origen_id=1;

